services:

  timetree-exporter:
    image: ghcr.io/poeschl/timetree-exporter:latest
    volumes:
      - ./test:/data
    environment:
      TIMETREE_EMAIL: "mail-timetree@poeschl.xyz" # The email address of the TimeTree account you want to export
      TIMETREE_PASSWORD: "H7Y0QFxF99%XNsz#" # The password of the TimeTree account you want to export
      TIMETREE_CALENDER_CODE: "vSREe7pxLbwE" # The calendar code of the calendar you want to export.
                                             # you can find it in the URL of the calendar (e.g. https://timetreeapp.com/calendars/vSREf7pxLbwE)

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./test:/usr/share/nginx/html:ro
    depends_on:
      - timetree-exporter

